/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pe.relari.view;

import com.pe.relari.service.EmployeeService;
import com.pe.relari.service.impl.EmployeeServiceImpl;
import com.pe.relari.util.EmployeeUtil;
import com.pe.relari.util.MyRender;
import java.awt.event.ActionEvent;

import java.util.Arrays;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import lombok.Getter;
import lombok.Setter;

/**
 * Class EmployeeReport.
 *
 * @author Relari
 */
public class EmployeeReport extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = -1024157165236900427L;
    private final DefaultTableModel defaultTableModel = new DefaultTableModel();
    private final EmployeeService employeeService = EmployeeServiceImpl.getInstance();

    @Setter
    @Getter
    private String nameEmployee;

    public EmployeeReport() {
        init();
    }

    public EmployeeReport(String nameEmployee) {
        init();

        this.nameEmployee = nameEmployee;
        
        System.out.println(getNameEmployee());
    }

    private void init() {
        initComponents();
        tableConfig();
        
        /**
         * Creates new form EmployeeReport
         */
        
        employeeService.findAll()
                .forEach(employee -> {
                    Object[] row = EmployeeUtil.rowEmployee(employee);
                    defaultTableModel.addRow(row);
                });

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        popupTable();

    }

    private void tableConfig() {
        Arrays.asList("Id", "Name", "Sex", "Status")
                .forEach(defaultTableModel::addColumn);

        this.tblEmployees.setModel(defaultTableModel);
        
        this.tblEmployees.setDefaultRenderer(Object.class, new MyRender());
    }
    
    private void popupTable() {
        JPopupMenu jPopupMenu = new JPopupMenu();
    
        JMenuItem itemDelete = new JMenuItem("Delete Register");
        itemDelete.addActionListener((ActionEvent actionEvent) -> {
            
            int option = JOptionPane.showConfirmDialog(rootPane, "Desea eliminar este registro", "", JOptionPane.YES_NO_OPTION);
            
            if (JOptionPane.YES_OPTION == option) {
                
                int rowSelected = this.tblEmployees.getSelectedRow();
                
                employeeService.deleteById(
                        Integer.valueOf(getRowValue(rowSelected, 0))
                );
                
                defaultTableModel.removeRow(rowSelected);
                
            }
        });
        
        JMenuItem itemActive = new JMenuItem("Active Employee");
        itemActive.addActionListener((ActionEvent actionEvent) -> {
            
            int option = JOptionPane.showConfirmDialog(rootPane, "Desea activar este registro", "", JOptionPane.YES_NO_OPTION);
            
            if (JOptionPane.YES_OPTION == option) {
                
                int rowSelected = this.tblEmployees.getSelectedRow();
                
                employeeService.activeById(
                        Integer.valueOf(getRowValue(rowSelected, 0))
                );
                
                defaultTableModel.removeRow(rowSelected);
                
            }
        });

        jPopupMenu.add(itemDelete);
        jPopupMenu.add(itemActive);
        tblEmployees.setComponentPopupMenu(jPopupMenu);
    }
    
    private void addValuesInField() {
        if (this.tblEmployees.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un usuario", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            int rowSelected = this.tblEmployees.getSelectedRow();
            this.jTextField1.setText(getRowValue(rowSelected, 0));
        }
    }
    
    private String getRowValue(int rowSelected, int position) {
        return this.tblEmployees.getValueAt(rowSelected, position).toString();
    }

    private void clearTable() {
        while (defaultTableModel.getRowCount() > 0) {
            defaultTableModel.removeRow(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "active", "inactive" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
        // TODO add your handling code here:
        addValuesInField();
    }//GEN-LAST:event_tblEmployeesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearTable();
        
        String value = this.jComboBox1.getSelectedItem().toString();
        
        employeeService.findByStatus(value.equals("active"))
                .forEach(employee -> {
                    Object[] row = EmployeeUtil.rowEmployee(employee);
                    defaultTableModel.addRow(row);
                });
        
        
        //employeeService.activeById(Integer.valueOf(this.jTextField1.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables
}
